### PR TITLE
UDT Metrics

### PR DESCRIPTION
**Pull request by Akilan1999**
## Displays the UDT Metrics:

Example:
```
Total HandShake Packets Sent:1 
Total HandShake Packets Received:0 
Total keep-alive Packets Sent:0 
Total keep-alive Packets Received:0 
Total ACK Packets Sent:151367 
Total ACK Packets Received:0 
Total NAK Packets Sent:115384 
Total NAK Packets Received:0 
Total Congestion Packets Sent:0 
Total Congestion Packets Received:0 
Total Shutdown Packets Sent:0 
Total Shutdown Packets Received:0 
Total ACK2 Packets Sent:0 
Total ACK2 Packets Received:149887 
Total Msg-drop Packets Sent:0 
Total Msg-drop Packets Received:0 
Total Error Packets Sent:0 
Total Error Packets Received:0 
Total User-defined Packets Sent:0 
Total User-define Packets Received:0 
Total Data Packets Sent:0 
Total Data Received:751682 
Total Other Packets Sent:0 
Total Other Packets Received:0 
Total Number Of Data packets attempted to get Processed:0 
Total Number Of Data packets out of order:0 
```

### CODE REVIEW

**Comment by Kleissner** [comment]
**Regarding prints**
`PrintMetrics` should not exist in my opinion - there should be no visible printfs in ANY sub library.

Also regular printfs don't show up in the embedded terminal of the browser, so it would not be visible anyways.

A companion function to format certain parameters would be fine in general, but I think it's out of place here. Printing statistics should be done by the client.

**if else if else if else if**
`packet.PacketTypeName(p.PacketType())` should be checked via switch statement. otherwise inefficient.

**Comment by Akilan1999** [comment]
## Changes done:
- ```PrintMetrics``` should not exist in my opinion - there should be no visible printfs in ANY sub library. Added to the Cmd library.
- ``` if else if else if else if```
```packet.PacketTypeName(p.PacketType())``` should be checked via switch statement. otherwise inefficient.  
   Changed to switch statement.
- ```Global vars```: Removed.

**Comment by Kleissner** [comment]
I am going to commit a few changes. One example: This is a nop, it returns a pointer to an internal var, not a copy. Therefore no point in not exporting metrics directly.
```go
func (s *UDTSocket) GetMetrics() *Metrics {
	return s.metrics
}
```

**Comment by Kleissner** [comment]
Making some other changes to the code for efficiency and removing commented out/unused code. Going to directly commit it instead of a PR.

**Pull request closed without merging**
